### PR TITLE
Implement various Math functions

### PR DESCRIPTION
**Pull request by thomas-alrek**
This pull request implements various math functions.

### Copy Value From Variable
Copies value from variable B into variable A
### Math Add
Adds value to variable
### Math Subtract
Subtracts value from variable
### Math Multiply
Multiplies variable by value
### Math Divide
Divides variable by value
### Math Modulo
Performs modulo on variable by value
### Math Add Variable
Adds value from variable B to variable A
### Math Subtract Variable
Subtracts variable A by value from variable B
### Math Multiply Variable
Multiplies variable A by value from variable B
### Math Divide Variable
Divides variable A by value from variable B
### Math Modulo Variable
Performs modulo on variable A by value from variable B

### CODE REVIEW

**Comment by WAUthethird** [comment]
Can you add comparisons, such as `var1 =< var2` and so on?

**Comment by thomas-alrek** [comment]
@WAUthethird Yeah, I updated the PR now with a "If Variable Compare" event

**Comment by chrismaltby** [comment]
Hi Thomas, was really hoping to get this one tested and merged today, from the little testing I managed to do it all seems to work great but without being able to see the values directly it was quite tedious (I was having to do If Value == 1 Display Text "One", If Value == 2 Display Text "Two" etc.) So I decided instead we needed #54 to be implemented to make this easier. Managed to get a bit of time today to implement that one which I've done in 4bc17c4169663e9bde372488c3671fa96c6f7390. So hopefully should get time to test this pull request and the other one you've submitted over the next day or two (it's my wedding anniversary tomorrow so probably shouldn't be doing too much on this!! :-D)

**Comment by thomas-alrek** [comment]
Great! Yeah, it should work. I testet it the same way as you described it. But have not been able to test it on other platforms yet. I have a working CircleCI config in my fork that I could PR to this repo if you like. That way you could always have up to date develop builds that you could link to.

**Comment by chrismaltby** [comment]
This all worked great, I've added a project for testing each math event in 1f554ef2885536d19f30a846277b373efca537fa.

**Pull request merged**
