### PR TITLE
Feature/i10n Norwegian

### PR DESCRIPTION
**Pull request by thomas-alrek**

### CODE REVIEW

**Comment by chrismaltby** [comment]
Hi Thomas, thanks for this. I'm not sure I can accept the change to l10n.js though as what you have there will prevent being able to do a British English override, or Portuguese vs Brazilian Portuguese etc. What value are you getting back from app.getLocale()? Can you change the pull request to name the json as what you get for that value and revert the l10n.js changes?

**Comment by thomas-alrek** [comment]
My bad. I was having some issues on my local device. But it seems to be working now. I have reverted the changes to l10n.js

**Comment by chrismaltby** [comment]
Thanks!

**Comment by chrismaltby** [comment]
By the way, I added a few more keys to en.json as part of e1b22b4c84932dfcf3b1c1d09d566890c97fa98e but you might want to hold off on doing those as I still need to go through the rest of the text and localise it, probably better if you're doing it in one go :-)

**Pull request merged**
