### PR TITLE
It localization v2beta

### PR DESCRIPTION
**Pull request by marcosecchi**
Update Italian Localization for GBStudio v2.

### CODE REVIEW

**Comment by marcosecchi** [comment]
@chrismaltby sorry to bother you, but I will soon be using GBStudio b2 for a workshop involving 17yo kids. Would it be possible to merge this pull request so they will have the full IDE in italian?

**Comment by RichardULZ** [comment]
@marcosecchi if you need them in a hurry and can live compile gbs from github, you could try building your own binaries

`yarn `<--- install dependencies
`npm start` <--- build and run the app live
`yarn make:win` or  `yarn make:mac` or just
`yarn make` <--- build the binaries
will save to GitHub\gb-studio\out\

**Comment by marcosecchi** [comment]
@RichardULZ Thanks but unfortunately I get this error when compiling:

```
An unhandled rejection has occurred inside Forge:
[Error: ENOENT: no such file or directory, rename 'C:\Users\MARCOS~1\AppData\Local\Temp\electron-packager\win32-x64\GB Studio-win32-x64\electron.exe' -> 'C:\Users\MARCOS~1\AppData\Local\Temp\electron-packager\win32-x64\GB Studio-win32-x64\gb-studio.exe'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'C:\\Users\\MARCOS~1\\AppData\\Local\\Temp\\electron-packager\\win32-x64\\GB Studio-win32-x64\\electron.exe',
  dest: 'C:\\Users\\MARCOS~1\\AppData\\Local\\Temp\\electron-packager\\win32-x64\\GB Studio-win32-x64\\gb-studio.exe'
}

Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
```

Do you have any advice on this?

Thanks.

**Comment by marcosecchi** [comment]
@RichardULZ thanks for the heads up. As the pull request is from Dec. 2020 and it's just a localization update, I was hoping for a merge any time.

Anyway, unfortunately the make command fails with the following error:

```
An unhandled rejection has occurred inside Forge:
[Error: ENOENT: no such file or directory, rename 'C:\Users\MARCOS~1\AppData\Local\Temp\electron-packager\win32-x64\GB Studio-win32-x64\electron.exe' -> 'C:\Users\MARCOS~1\AppData\Local\Temp\electron-packager\win32-x64\GB Studio-win32-x64\gb-studio.exe'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'C:\\Users\\MARCOS~1\\AppData\\Local\\Temp\\electron-packager\\win32-x64\\GB Studio-win32-x64\\electron.exe',
  dest: 'C:\\Users\\MARCOS~1\\AppData\\Local\\Temp\\electron-packager\\win32-x64\\GB Studio-win32-x64\\gb-studio.exe'
}

Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
```

Do you have any hint on how to solve this?

Thanks

**Pull request closed without merging**
