### PR TITLE
Add "If Current Scene Is" event

### PR DESCRIPTION
**Pull request by patrickmollohan**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](/chrismaltby/gb-studio/blob/develop/.github/COMMIT_MESSAGE_GUIDELINES.md)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds "If Current Scene Is" event, which checks if the current scene equals the selected scene.

* **What is the current behavior?** (You can also link to an open issue here)
No way to check if the current scene is a specific scene aside from using variables and assigning each scene a value.

* **What is the new behavior (if this is a feature change)?**
Can now check if the current scene is a specific scene.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
None that I am aware of.

* **Other information**:

### CODE REVIEW

**Comment by maxoakland** [comment]
This is great! I’ve been wanting this

**Comment by patrickmollohan** [comment]
Thanks, I'm glad to hear so! Hope you get to use it soon!

**Comment by chrismaltby** [comment]
Hi @patrickmollohan unfortunately because you've got the condition checking happening at compile time it doesn't work if you use it within a custom script as all the same compiled script is used for all scenes. It does work if you add the script directly into a scene but I image most use cases would probably want to have the check in a shared script.

Instead I think you'd need to read the value from `far_ptr_t current_scene` from `data_manager.c` and compare the `current_scene.bank` and `current_scene.ptr` match the corresponding values for the selected scene.

I'll have a go at making this change and see if it works.

**Comment by chrismaltby** [comment]
Hi @patrickmollohan I've just modified this to use a runtime check rather than a compile time one. Seems like it should work. 

Do you mind testing at your end too and if this is also working for you then I can merge.

**Comment by patrickmollohan** [comment]
@chrismaltby oh, right! That makes sense. Sorry about that; I guess I never tried using it in a custom script before, but that makes a lot more sense now. Based on my testing, everything appears to be working perfectly now!

**Pull request merged**
