### PR TITLE
Optional vertical shake

### PR DESCRIPTION
**Pull request by Xeyler**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](/chrismaltby/gb-studio/blob/develop/.github/COMMIT_MESSAGE_GUIDELINES.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features) 

Note: I was unable to find in-depth documentation alongside the code. I would be happy to update the relevant doc sources if someone could point me towards them!

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR implements the "vertical screen shake" feature which has been requested several times. See: #175, #557 

* **What is the current behavior?** (You can also link to an open issue here)

Currently, GB Studio only supports shaking the camera horizontally.

* **What is the new behavior (if this is a feature change)?**

This feature adds X and Y checkboxes to the camera shake command, allowing the user to shake the camera on the horizontal axis, vertical axis, or both axes.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

The way I've introduced this change, the camera shake command behaves the same way by default until the user has changed the axes options.

* **Other information**:

Here's what a new camera shake with the horizontal and vertical axes enabled looks like! Note that my gif recorder slows down the motion.

xy-shake

Please let me know if any of the changes I've made are unsatisfactory. This is my first pull request on this repo, so I'm not as familiar with the codebase as I would be otherwise.

### CODE REVIEW

**Comment by chrismaltby** [comment]
Great! Thanks I've had a quick skim through the code and it looks good so far. I'll do some testing soon and will let you know how I get on.

In terms of code documentation there's not really anything just yet, it's been on my todo list for a long time but to be honest I should probably just remove that line from the the PR template for now!

**Comment by Xeyler** [comment]
Ah, I'm glad you like my PR! 😄🍰

I've just realized that with the changes I've made, entities don't shake on the vertical axis. I'm not sure how I missed this... And come to think of it, it's weird that my changes would introduce this behavior... I'll take another look at the engine when I catch a second.

If you find any other oversights or issues, please let me know! I'll be happy to rework my changes.

**Comment by Xeyler** [comment]
Alright, with my latest commit, actors now shake on the vertical axis. And I've just checked: With my changes to the tests, `npm test` reports all are passing.

With that, I think this PR is ready to merge unless there are further comments about coding style, design decisions, or test coverage. 

Otherwise, thanks for having me! I've haven't used GB Studio much at all to be honest. In my projects, I've used straight assembly. Learning more about GBDK and GB Studio has been super cool... I'll have to experiment with them more! :heart: :video_game:

**Comment by patrickmollohan** [comment]
Great work! No issues as far as I can tell from the projects I've tested this with.
One suggestion: I'd either make the X and Y checkboxes inline with each other (should just need to add `width: "50%",` to `"shouldShakeX"` and `"shouldShakeY"` fields in `src/lib/events/eventCameraShake.js` ), or perhaps a better approach, have a dropdown to select between "Horizontal", "Vertical", and "Diagonal". This would be more consistent with other areas of GB Studio, such as the dropdown in "Actor: Move To" and would eliminate the case where neither X or Y is checked (as I'm typing this, it occurs to me I haven't tested what that does).
Aside from that, it would be amazing to have this in GB Studio!

**Comment by Xeyler** [comment]
The case where neither X or Y is checked is a strange one. Typically, it just won't shake at all (unless I'm wrong about my own code :sweat_drops:). 

However, if the project was started in a version of GB Studio which doesn't have the changes of my fork, then it's opened in my fork, the X and Y checkboxes won't be checked. But by default, only the horizontal axis will shake (to preserve the expected behavior).

I should spend some time to fix it so that when older projects are opened, the X checkbox is ticked and the Y checkbox isn't. And perhaps I should change it to be a dropdown so that the non-shake shake isn't possible?

**Comment by patrickmollohan** [comment]
Just implemented the dropdown:
```
const l10n = require("../helpers/l10n").default;

const id = "EVENT_CAMERA_SHAKE";

const fields = [
  {
    key: "time",
    type: "number",
    label: l10n("FIELD_SECONDS"),
    width: "50%",
    min: 0,
    max: 10,
    step: 0.1,
    defaultValue: 0.5
  },
  {
    key: "shakeDirection",
    label: l10n("FIELD_DIRECTION"),
    width: "50%",
    type: "select",
    options: [
      ["horizontal", "↔ " + l10n("FIELD_HORIZONTAL")],
      ["vertical", "↕ " + l10n("FIELD_VERTICAL")],
      ["diagonal", "⤡ " + l10n("FIELD_DIAGONAL")]
    ],
    defaultValue: "horizontal"
  }
];

const compile = (input, helpers) => {
  const { cameraShake } = helpers;
  let seconds = typeof input.time === "number" ? input.time : 0.5;
  let shakeDirection = input.shakeDirection;
  let shouldShakeX = true;
  let shouldShakeY = false;
  switch (shakeDirection) {
  	case "horizontal":
  		shouldShakeX = true;
  		shouldShakeY = false;
  		break;
  	case "vertical":
  		shouldShakeX = false;
  		shouldShakeY = true;
  		break;
  	case "diagonal":
  		shouldShakeX = true;
  		shouldShakeY = true;
  		break;
  	default:
  		shouldShakeX = true;
  		shouldShakeY = false;
  }
  // Convert seconds into frames (60fps)
  while (seconds > 0) {
    const time = Math.min(seconds, 1);
    cameraShake(shouldShakeX, shouldShakeY, Math.ceil(60 * time));
    seconds -= time;
  }
};

module.exports = {
  id,
  fields,
  compile
};
```
From there, the localisations would need "FIELD_HORIZONTAL": "Horizontal" and "FIELD_VERTICAL": "Vertical" added in the respective languages.

**Comment by chrismaltby** [comment]
Thanks @Xeyler this is working great! I've just made the changes @patrickmollohan suggested making the event use a dropdown, and I've added this to the engine changelog so if anyone had ejected their engine they can see which files have been updated.

**Pull request merged**
