### PR TITLE
Override default button input when attaching script

### PR DESCRIPTION
**Pull request by pau-tomas**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](/chrismaltby/gb-studio/blob/develop/.github/COMMIT_MESSAGE_GUIDELINES.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix / feature ?

* **What is the current behavior?** (You can also link to an open issue here)

In 1.2 using "Attach script to button" disabled the default behavior for the button. So, attaching a script to A will disable the interaction with actors.

In 2.0 when attaching, the engine will try to run the two scripts in the background which lead to some unexpected issues like the player moving even if the directional buttons had an script attached ( #452 , #502 ).

* **What is the new behavior (if this is a feature change)?**

This patch restores the 1.2 behavior. Attached scripts override the default input behavior except when a dialogue/menu is shown.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Maybe. Some people might be using the new default behavior of 2.0 (see below for potential solution and issue).

* **Other information**:

It'd be simple to add a checkbox to the attach input script with the option to override or not the default behavior. This would work ok for the direction buttons, but not for `A` as without this patch the default behavior (ie: interacting with an actor) is only called if the button is pressed repeatedly. 

The implementation is a bit convoluted and repetitive and I'm not a big fan of exposing `ui_block` to `Input.h`, but I couldn't think of a more elegant way.

### CODE REVIEW

**Comment by patrickmollohan** [comment]
I've been looking forward to this! A great way to disable player movement, for instance, by attaching an empty script to the D-Pad buttons. Awesome! Seems to work on my projects quite well.
This is somewhat related: I made an adjustment to the Script_SetInputScript_b() with your modifications so the same script can be attached easily to multiple buttons.
```
void Script_SetInputScript_b() {
  UBYTE input, index;

  input = script_cmd_args[0];

  if (script_cmd_args[1]) {
    SET_BIT_MASK(input_script_persist, input);
  } else {
    UNSET_BIT_MASK(input_script_persist, input);
  }

  SET_BIT_MASK(input_override_default, input);

  index = 0;
  for (index = 0; index != 8; ++index) {
    if (input & 1) {
      input_script_ptrs[index].bank = script_cmd_args[2];
      input_script_ptrs[index].offset = (script_cmd_args[3] * 256) + script_cmd_args[4];
    }
    input = input >> 1;
  }
}
```
eventInputScriptSet.js would need its `defaultValue` property changed from `"b"` to `["b"]` in the `input` field. I don't know if this would break anything, but with simple tests such as an empty script or shaking the camera when one of several buttons is pressed seems to work as expected. Also tested removing the script and that works when removing the script from all buttons or some of them. I don't know if this warrants a separate pull request or if you think it'd be worth implementing, but I was hoping to get your input (pun semi-intended) since you probably know the input system better than I do.

**Comment by pau-tomas** [comment]
Thanks for testing it @patrickmollohan !

I like the idea of being able to add one script to multiple inputs and I think it should be a separate PR. I'm not sure if it'll require a migration script to update all the existing single inputs (`"b"`) to arrays of single item (`["b"]`).

**Comment by Bastani** [comment]
This would help a lot in my project, I've been using a Boolean variable to counteract the current behavior.

**Comment by chrismaltby** [comment]
Thanks @pau-tomas In testing there's one little bug I found is if you set a Text / Menu event to a direction button the ALLOW_DEFAULT macros return true for 1 frame, because the input script sets ui_block to true which allows the normal movement in the scene's update script just for that frame.

Screenshot 2020-10-06 at 20 46 06

If you update Core_Main.c to move `HandleInputScripts()` to be after the scene update it fixes it:

```
    if (!script_ctxs[0].script_ptr_bank && !ui_block) {      
      PUSH_BANK(stateBanks[scene_type]);
      updateFuncs[scene_type]();
      POP_BANK;
      HandleInputScripts();
    }
```

Do you think this will cause any issues for anyone though? I can't think of any cases where the order of these should introduce any new bugs but it's not impossible.

I guess it could become this instead but feels pretty ugly to do an extra check there if the other way works.

```
    if (!script_ctxs[0].script_ptr_bank && !ui_block) {   
      HandleInputScripts();   
      if (!ui_block) {
          PUSH_BANK(stateBanks[scene_type]);
          updateFuncs[scene_type]();
          POP_BANK;
      }
    }
```

Once you make that change though these seems to work great!

Are you also okay to update `src/lib/project/ejectEngineChangelog.ts` to add a `2.0.0-e6` to that list with the list of files that's changed so people know what to update in their ejected engines?

Thanks!

**Comment by pau-tomas** [comment]
Thanks for checking Chris! 

I can't think of a case where changing the order of the calls might break things either. If anything it seem to make things more consistent in case, in the future, we introduce the option to not override the default behavior, as instead of being called if the button is pressed repeatedly it seems to do it always.

**Comment by chrismaltby** [comment]
I'm all for automating that process if you've got an idea how 😁 I've never used Github actions before either so very interested to see if this would be possible!

**Comment by pau-tomas** [comment]
Merged #595 (thanks @patrickmollohan!) and updated engine version and changelog (manually, for now :D )

**Comment by chrismaltby** [comment]
Awesome thanks @pau-tomas and @patrickmollohan all works great!

**Pull request merged**
