### PR TITLE
Add chinese translate by zh-CN

### PR DESCRIPTION
**Pull request by InchouRyu**
{
  "RTL": false,

  "// 1": "UI -------------------------------------------------------",
  "ACTOR": "演员",
  "TRIGGER": "触发器",
  "SCENE": "场景",
  "PROJECT": "项目",

  "// 2": "Navigator ------------------------------------------------",
  "NAV_GAME_WORLD": "主界面",
  "NAV_SPRITES": "精灵",
  "NAV_BACKGROUNDS": "背景",
  "NAV_UI_ELEMENTS": "UI元素",
  "NAV_MUSIC": "音乐",
  "NAV_SCRIPT_REVIEW": "脚本审查",
  "NAV_BUILD_AND_RUN": "搭建并运行",

  "// 3": "Toolbar --------------------------------------------------",
  "TOOLBAR_MODIFIED": "修改",
  "TOOLBAR_ZOOM_IN": "放大",		
  "TOOLBAR_ZOOM_OUT": "缩小",
  "TOOLBAR_ZOOM_RESET": "还原缩放",
  "TOOLBAR_OPEN_PROJECT_FOLDER": "打开文件夹",
  "TOOLBAR_EXPORT_AS": "导出为…",
  "TOOLBAR_EXPORT_ROM": "导出为ROM",
  "TOOLBAR_EXPORT_WEB": "导出为Web",
  "TOOLBAR_RUN": "运行",

  "// 4": "Tools ----------------------------------------------------",
  "TOOL_SELECT_LABEL": "选择",
  "TOOL_ADD_LABEL": "添加",
  "TOOL_ADD_ACTOR_LABEL": "演员",
  "TOOL_ADD_TRIGGER_LABEL": "触发器",
  "TOOL_ADD_SCENE_LABEL": "场景",
  "TOOL_ERASER_LABEL": "橡皮擦",
  "TOOL_COLLISIONS_LABEL": "碰撞块",

  "// 5": "Editors --------------------------------------------------",
  "SIDEBAR_NAVIGATION": "导航",
  "SIDEBAR_STARTING_SCENE": "开始场景",
  "SIDEBAR_SCENE_START_SCRIPT": "场景脚本",
  "SIDEBAR_ACTOR_SCRIPT": "演员脚本",
  "SIDEBAR_TRIGGER_SCRIPT": "触发器脚本",
  "SIDEBAR_ADD_EVENT": "添加事件",

  "// 6": "Form Fields ----------------------------------------------",
  "FIELD_NAME": "名称",
  "FIELD_AUTHOR": "作者",
  "FIELD_NOTES": "备注",
  "FIELD_ADD_NOTES": "添加备注",
  "FIELD_TYPE": "类型",
  "FIELD_ACTOR_INVOKE": "执行演员绑定的脚本",
  "FIELD_BACKGROUND": "背景",
  "FIELD_SPRITE_SHEET": "精灵图片",
  "FIELD_PLAYER_SPRITE_SHEET": "玩家精灵图片",
  "FIELD_MOVEMENT_TYPE": "移动方式",
  "FIELD_MOVEMENT_SPEED": "移动速度",
  "FIELD_ANIMATION_SPEED": "动画速度",
  "FIELD_DIRECTION": "方向",
  "FIELD_X": "X",
  "FIELD_Y": "Y",
  "FIELD_WIDTH": "宽度",
  "FIELD_HEIGHT": "高度",
  "FIELD_DIRECTION_UP": "上",
  "FIELD_DIRECTION_DOWN": "下",
  "FIELD_DIRECTION_LEFT": "左",
  "FIELD_DIRECTION_RIGHT": "右",
  "FIELD_FADE_SPEED": "消隐速度",
  "FIELD_SPEED": "速度",
  "FIELD_FASTER": "快速",
  "FIELD_SLOWER": "慢速",
  "FIELD_SCENE_PUSH_STATE_DESCRIPTION": "将场景数据推进堆栈。",
  "FIELD_SCENE_POP_STATE_DESCRIPTION": "将顶部场景数据从堆栈抛出。",
  "FIELD_SCENE_POP_ALL_STATE_DESCRIPTION": "将全部场景数据从堆栈抛出。",
  "FIELD_SCENE_RESET_STATE_DESCRIPTION": "清除堆栈内所有已保存的场景数据。",
  "FIELD_SLIDE_UNTIL_COLLISION": "滑动到发生碰撞为止",
  "FIELD_LOOP": "循环",
  "FIELD_SECONDS": "秒",
  "FIELD_SET_TRUE_IF": "设为“True”如果",
  "FIELD_SET_FALSE_IF": "设为“False”如果",
  "FIELD_CHOICE_A": "选项A",
  "FIELD_CHOICE_B": "选项B",
  "FIELD_VALUE": "值",
  "FIELD_MIN_VALUE": "最小值",
  "FIELD_MAX_VALUE": "最大值",
  "FIELD_RENAME": "重命名",
  "FIELD_SAVE": "保存",
  "FIELD_VARIABLE_NAME": "变量名",
  "FIELD_RESET_VARIABLES": "重置全部变变量为“False”。",
  "FIELD_LOOP_EXIT": "结束循环请使用“停止脚本”或者“切换场景”。",
  "FIELD_OVERLAY_HIDE": "从屏幕隐藏遮罩层窗口。",
  "FIELD_UNHIDE_SPRITES": "显示全部活动精灵。",
  "FIELD_HIDE_SPRITES": "从屏幕隐藏全部精灵。",
  "FIELD_ANY_OF": "任何",
  "FIELD_TEXT_PLACEHOLDER": "请输入…",
  "FIELD_STOP_MUSIC": "停止之前播放的全部音乐。",
  "FIELD_STOP_SCRIPT": "停止当前运行的脚本",
  "FIELD_LOAD_DATA": "读取游戏数据。",
  "FIELD_SAVE_DATA": "保存当前游戏数据。 需要卡带类型含有BATTERY。",
  "FIELD_CLEAR_DATA": "清除全部已保存的游戏数据。",
  "FIELD_IF_SAVED_DATA": "当玩家保存游戏时开始运行。",
  "FIELD_MOVEMENT_STATIC": "静态",
  "FIELD_MOVEMENT_FACE_INTERACTION": "面对面交互",
  "FIELD_MOVEMENT_RANDOM_ROTATION": "随机旋转",
  "FIELD_MOVEMENT_RANDOM_WALK": "随机走动",
  "FIELD_ADD_VALUE": "加上",
  "FIELD_ADD_VALUE_FROM": "添加变量",
  "FIELD_TO_VARIABLE": "到变量",
  "FIELD_BY_VALUE": "从值",
  "FIELD_SUB_VALUE": "减去",
  "FIELD_FROM_VARIABLE": "从变量",
  "FIELD_MUL_VARIABLE": "乘以",
  "FIELD_DIV_VARIABLE": "除以",
  "FIELD_MOD_VARIABLE": "取模",
  "FIELD_SPRITE_ANIMATED_ACTORS": "动画演员",
  "FIELD_SPRITE_ACTORS": "演员",
  "FIELD_SPRITES": "精灵",
  "FIELD_SPRITE_FRAMES": "帧",
  "FIELD_ANIMATE_WHEN_STATIONARY": "静止时开始动画",
  "FIELD_ANIMATE_FRAMES": "通过循环帧动画",
  "TEXT_SPEED_IN": "文本打开速度",
  "TEXT_SPEED_OUT": "文本关闭速度",
  "TEXT_SPEED": "文本显示速度",
  "FIELD_LABEL": "标签",
  "FIELD_ON_PRESS": "按下",
  "FIELD_REMOVE_INPUT_SCRIPT_ON": "移除控制器按钮绑定的脚本",
  "FIELD_ANIMATION_FRAME": "动画帧",
  "FIELD_INITIAL_FRAME": "初始帧",
  "FIELD_MATH_NOTE": "Note: 变量的最大值为255，如果高于255或低于0则会折行。",
  "FIELD_TRUE": "True",
  "FIELD_FALSE": "False",
  "FIELD_VARIABLE": "变量",
  "FIELD_RANDOM": "随机",
  "FIELD_SET_TO": "设置为",

  "// 7": "Asset Viewer ---------------------------------------------",
  "ASSET_SEARCH": "搜索",
  "ASSET_EDIT": "编辑",
  "ASSET_ADD": "添加",

  "// 8": "Build ----------------------------------------------------",
  "BUILD_RUN": "运行",
  "BUILD_EXPORT_ROM": "导出为ROM",
  "BUILD_EXPORT_WEB": "导出为Web",
  "BUILD_CLEAR": "清除",

  "// 9": "Scripting Events -----------------------------------------",
  "EVENT_SWITCH_SCENE": "切换场景",
  "EVENT_WAIT": "等待",
  "EVENT_CAMERA_SHAKE": "镜头抖动",
  "EVENT_IF_TRUE": "如果变量为“True”",
  "EVENT_IF_FALSE": "如果变量为“False”",
  "EVENT_IF_VALUE": "如果变量与值相比",
  "EVENT_IF_VALUE_COMPARE": "如果变量与变量相比",
  "EVENT_IF_INPUT": "如果控制器按下",
  "EVENT_IF_ACTOR_AT_POSITION": "如果演员处在某位置",
  "EVENT_IF_ACTOR_DIRECTION": "如果演员朝向某方向",
  "EVENT_SET_TRUE": "变量设为“True”",
  "EVENT_SET_FALSE": "变量设为“False”",
  "EVENT_SET_VALUE": "变量设为值",
  "EVENT_COPY_VALUE": "从某个变量复制值",
  "EVENT_SET_RANDOM_VALUE": "变量设为随机值",
  "EVENT_INC_VALUE": "变量增加1",
  "EVENT_DEC_VALUE": "变量减少1",
  "EVENT_MATH_ADD": "加法",
  "EVENT_MATH_SUB": "减法",
  "EVENT_MATH_MUL": "乘法",
  "EVENT_MATH_DIV": "除法",
  "EVENT_MATH_MOD": "取模",
  "EVENT_MATH_ADD_VALUE": "变量加法",
  "EVENT_MATH_SUB_VALUE": "变量减法",
  "EVENT_MATH_MUL_VALUE": "变量乘法",
  "EVENT_MATH_DIV_VALUE": "变量除法",
  "EVENT_MATH_MOD_VALUE": "变量取模",
  "EVENT_SCENE_PUSH_STATE": "保存当前场景于堆栈",
  "EVENT_SCENE_POP_STATE": "Scene: 从堆栈恢复上一个场景",
  "EVENT_SCENE_POP_ALL_STATE": "从堆栈恢复第一个场景",
  "EVENT_SCENE_RESET_STATE": "清空场景堆栈",
  "EVENT_CHOICE": "显示多选文本",
  "EVENT_RESET_VARIABLES": "重置全部变量为“False”",
  "EVENT_LOOP": "无限循环",
  "EVENT_GROUP": "事件群组",
  "EVENT_TEXT": "显示对话文本",
  "EVENT_CAMERA_MOVE_TO": "镜头移动至",
  "EVENT_CAMERA_LOCK": "镜头锁定于玩家",
  "EVENT_FADE_IN": "场景淡入",
  "EVENT_FADE_OUT": "场景淡出",
  "EVENT_ACTOR_SET_DIRECTION": "设置演员朝向",
  "EVENT_ACTOR_SET_POSITION": "设置演员位置",
  "EVENT_ACTOR_SET_POSITION_RELATIVE": "设置演员相对位置",
  "EVENT_ACTOR_GET_POSITION": "保存演员位置值于变量",
  "EVENT_ACTOR_SET_POSITION_TO_VALUE": "使用变量设置演员于位置",
  "EVENT_ACTOR_MOVE_TO": "演员移动至",
  "EVENT_ACTOR_MOVE_RELATIVE": "演员相对移动",
  "EVENT_ACTOR_MOVE_TO_VALUE": "使用变量移动演员至位置",
  "EVENT_ACTOR_PUSH": "演员远离玩家",
  "EVENT_ACTOR_EMOTE": "演员使用表情气泡",
  "EVENT_ACTOR_SHOW": "显示演员",
  "EVENT_ACTOR_HIDE": "隐藏演员",
  "EVENT_ACTOR_INVOKE": "调用演员脚本",
  "EVENT_PLAYER_SET_SPRITE": "设置玩家精灵图片",
  "EVENT_SHOW_SPRITES": "显示全部精灵",
  "EVENT_HIDE_SPRITES": "隐藏全部精灵",
  "EVENT_OVERLAY_SHOW": "显示遮罩层",
  "EVENT_OVERLAY_HIDE": "隐藏遮罩层",
  "EVENT_OVERLAY_MOVE_TO": "遮罩层移动至",
  "EVENT_AWAIT_INPUT": "暂停脚本直到控制器被按下",
  "EVENT_MUSIC_PLAY": "播放音乐",
  "EVENT_MUSIC_STOP": "停止音乐",
  "EVENT_STOP": "停止脚本",
  "EVENT_LOAD_DATA": "载入游戏数据",
  "EVENT_SAVE_DATA": "保存游戏数据",
  "EVENT_CLEAR_DATA": "清除游戏数据",
  "EVENT_IF_SAVED_DATA": "如果游戏数据已保存",
  "EVENT_ACTOR_SET_MOVEMENT_SPEED": "设置演员移动速度",
  "EVENT_ACTOR_SET_ANIMATION_SPEED": "设置演员动画速度",
  "EVENT_TEXT_SET_ANIMATION_SPEED": "设置文本动画速度",
  "EVENT_SET_INPUT_SCRIPT": "为控制器按钮绑定脚本",
  "EVENT_REMOVE_INPUT_SCRIPT": "移除控制器按钮绑定的脚本",
  "EVENT_ACTOR_SET_FRAME": "设置演员动画帧",
  "EVENT_VARIABLE_MATH": "数学变量功能",

  "// 10": "Menu -----------------------------------------------------",

  "MENU_FILE": "文件",
  "MENU_NEW_PROJECT": "新建项目",
  "MENU_OPEN": "打开",
  "MENU_SAVE": "保存",
  "MENU_EDIT": "编辑",
  "MENU_UNDO": "还原",
  "MENU_REDO": "重做",
  "MENU_GAME": "游戏",
  "MENU_RUN": "运行",
  "MENU_EXPORT_AS": "导出为",
  "MENU_EXPORT_ROM": "导出为ROM",
  "MENU_EXPORT_WEB": "导出为Web",
  "MENU_VIEW": "视图",
  "MENU_GAME_WORLD": "主界面",
  "MENU_SPRITES": "精灵",
  "MENU_BACKGROUNDS": "背景",
  "MENU_UI_ELEMENTS": "UI元素",
  "MENU_MUSIC": "音乐",
  "MENU_SCRIPT_REVIEW": "脚本审查",
  "MENU_BUILD_AND_RUN": "搭建并运行",
  "MENU_THEME": "主题",
  "MENU_THEME_DEFAULT": "系统默认",
  "MENU_THEME_LIGHT": "浅色",
  "MENU_THEME_DARK": "深色",
  "MENU_SHOW_COLLISIONS": "显示碰撞块",
  "MENU_SHOW_CONNECTIONS": "显示关联线",
  "MENU_ZOOM_RESET": "实际大小",
  "MENU_ZOOM_IN": "放大",
  "MENU_ZOOM_OUT": "缩小",
  "MENU_DOCUMENTATION": "帮助文档",
  "MENU_LEARN_MORE": "了解更多",
  "MENU_SPEECH": "语言",
  "MENU_ABOUT": "关于GB Studio",
  "MENU_CART_TYPE": "卡带类型",
  "MENU_COPY_EVENT": "复制事件",
  "MENU_RENAME_EVENT": "重命名事件",
  "MENU_PASTE_VALUES": "粘贴值",
  "MENU_PASTE_EVENT_BEFORE": "在前面粘贴事件",
  "MENU_PASTE_EVENT_AFTER": "在后面粘贴事件",
  "MENU_DELETE_EVENT": "删除事件",
  "MENU_COPY_SCRIPT": "复制脚本",
  "MENU_REPLACE_SCRIPT": "替换脚本",
  "MENU_PASTE_SCRIPT_BEFORE": "在前面粘贴脚本",
  "MENU_PASTE_SCRIPT_AFTER": "在后面粘贴脚本",
  "MENU_DELETE_SCRIPT": "删除脚本",
  "MENU_COPY_ACTOR": "复制演员",
  "MENU_PASTE_ACTOR": "粘贴演员",
  "MENU_DELETE_ACTOR": "删除演员",
  "MENU_COPY_TRIGGER": "复制触发器",
  "MENU_PASTE_TRIGGER": "粘贴触发器",
  "MENU_DELETE_TRIGGER": "删除触发器",
  "MENU_COPY_SCENE": "复制场景",
  "MENU_PASTE_SCENE": "粘贴场景",
  "MENU_DELETE_SCENE": "删除场景",

  "// 11": "Warnings -----------------------------------------------------",

  "WARNING_BACKGROUND_TOO_SMALL": "背景图不可小于160px x 144px",
  "WARNING_BACKGROUND_TOO_LARGE": "背景图不可大于256px x 256px",
  "WARNING_BACKGROUND_NOT_MULTIPLE_OF_8": "背景尺寸不是8的倍数",

  "// 12": "Errors -------------------------------------------------------",

  "ERROR_PLEASE_ENTER_PROJECT_NAME": "请输入项目名称",
  "ERROR_PLEASE_ENTER_PROJECT_PATH": "请输入项目路径",
  "ERROR_PROJECT_ALREADY_EXISTS": "项目已存在",
  "ERROR_INVALID_FILE_TYPE": "无效的文件类型",
  "ERROR_OPEN_GBSPROJ_FILE": "请选择.gbsproj或者.json文件",
  "ERROR_MISSING_PROJECT": "项目文件未找到",
  "ERROR_MOVED_OR_DELETED": "它可能被移动到了其他地方或者已被删除",

  "// 13": "Splash -------------------------------------------------------",

  "SPLASH_NEW": "新建",
  "SPLASH_OPEN": "打开",
  "SPLASH_RECENT": "最近打开",
  "SPLASH_PROJECT_NAME": "项目名称",
  "SPLASH_DEFAULT_PROJECT_NAME": "未命名",
  "SPLASH_PROJECT_TEMPLATE": "模板",
  "SPLASH_SAMPLE_PROJECT": "演示项目",
  "SPLASH_BLANK_PROJECT": "空白项目",
  "SPLASH_PATH": "路径",
  "SPLASH_CREATE": "建立",
  "SPLASH_CREATING": "建立中…",
  "SPLASH_CLEAR_RECENT": "清除历史记录",
  "SPLASH_NO_RECENT_PROJECTS": "最近没有打开任何项目。",

  "// 14": "Script Review ------------------------------------------------",

  "SCRIPT_REVIEW": "脚本审查",
  "SCRIPT_LINE": "Line",
  "SCRIPT_LINES": "Lines",
  "SCRIPT_WORD": "Word",
  "SCRIPT_WORDS": "Words"
}

### CODE REVIEW

**Comment by InchouRyu** [comment]
I don't know how to merge my repositories files to this project，sorry，If this is a wrong operation, please close it and I’ll commit to ISSUES.

**Comment by chrismaltby** [comment]
I don't know quite how you made this pull request but it seems to have gone pretty wrong! :-D
I've copied the translation you supplied into the latest dev build, there's a been a few more strings added since you translated though (I'm hoping this is everything for a little while) would you also be able to supply translations for the following? (You can just comment here)

```
  "MENU_CHECK_FOR_UPDATES": "Check For Updates...",
  "// 15": "Dialogs ------------------------------------------------------",
  "DIALOG_DOWNLOAD": "Download",
  "DIALOG_SKIP_VERSION": "Skip This Version",
  "DIALOG_REMIND_LATER": "Remind Me Later",
  "DIALOG_OK": "OK",
  "DIALOG_CANCEL": "Cancel",
  "DIALOG_UPDATE_AVAILABLE": "Update available",
  "DIALOG_UPDATE_DESCRIPTION": "GB Studio {version} available. Would you like to update?",
  "DIALOG_UPDATE_DONT_ASK_AGAIN": "Dont ask me again",
  "DIALOG_UP_TO_DATE": "You’re up-to-date!",
  "DIALOG_NEWEST_VERSION_AVAILABLE": "GB Studio {version} is currently the newest version available.",
  "DIALOG_UNABLE_TO_CHECK_LATEST_VERSION": "Unable to check latest version at the moment",
```

**Comment by InchouRyu** [comment]
:-D :-D :-D :-D
> 
> ```
>   "MENU_CHECK_FOR_UPDATES": "检查更新…",
>   "// 15": "Dialogs ------------------------------------------------------",
>   "DIALOG_DOWNLOAD": "下载",
>   "DIALOG_SKIP_VERSION": "跳过此版本",
>   "DIALOG_REMIND_LATER": "稍后提醒我",
>   "DIALOG_OK": "确定",
>   "DIALOG_CANCEL": "取消",
>   "DIALOG_UPDATE_AVAILABLE": "有可用的更新",
>   "DIALOG_UPDATE_DESCRIPTION": "GB Studio {version} 已准备好. 现在就要更新吗？",
>   "DIALOG_UPDATE_DONT_ASK_AGAIN": "下次不再询问",
>   "DIALOG_UP_TO_DATE": "当前已是最新版本！",
>   "DIALOG_NEWEST_VERSION_AVAILABLE": "GB Studio {version} 已是现在最新的版本。",
>   "DIALOG_UNABLE_TO_CHECK_LATEST_VERSION": "当前无法检查更新",
> ```

**Comment by chrismaltby** [comment]
Great 👍 that's included in the dev build now in commit bdb971c0e3ec398432a728f2732d0dd118533388

**Pull request closed without merging**
