### PR TITLE
Add support for launching projectile towards target actor

### PR DESCRIPTION
**Pull request by pau-tomas**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature

* **What is the current behavior?** (You can also link to an open issue here)

The only way to launch a projectile towards the position of an actor is by using ATAN2 in a GBVM event (introduced in 3.2)

* **What is the new behavior (if this is a feature change)?**

A new `Target` option in the Direction field for the Launch projectile event 

launch_projectile_target

Also added a new event field type for angles that displays the degrees (it's a common question in Discord about how angles work) and support for `atan2` to the Math expression events.

image

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

### CODE REVIEW

**Comment by patrickmollohan** [comment]
Already opened a PR for this a while ago: #1182. Love the angle field and atan2 math expression though!

**Comment by pau-tomas** [comment]
Oh! I didn't notice! I'll rebase on top of yours and we can merge this one first

**Comment by patrickmollohan** [comment]
Haha no worries, even I had to search for it! Sounds like a plan!

**Comment by pau-tomas** [comment]
Thanks! I rebased into this one. All should work without conflicts if your PR gets merged first. 

I fixed an issue for custom events. On the event if other actor id key isn't unique it won't be detected as an actor parameter inside the custom events. I renamed the key from `otherActorId` to `targetActorId`.

Other than that there's only some minor differences in naming (Actor Pos vs Target) which I don't feel super strong so I'll let @chrismaltby decide on that one.

**Comment by patrickmollohan** [comment]
Awesome work! Thanks for fixing up the issue as well; I think I ran into that before and couldn't figure out why. Makes sense now haha. I really need to go through my old PRs and clean them up a touch.

Actually, I like "Target"; I think that might be better than my attempts at naming things. I'd be totally good with renaming it to "Target" if Chris is!

**Comment by chrismaltby** [comment]
I went with this PR in the end but updated the changelog to credit you both :-)

**Pull request merged**
