### PR TITLE
A bit more refactoring of UI_b.c

### PR DESCRIPTION
**Pull request by untoxa**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our [guidelines](/chrismaltby/gb-studio/blob/develop/.github/COMMIT_MESSAGE_GUIDELINES.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
A bit more refactoring of UI_b.c

* **What is the current behavior?** (You can also link to an open issue here)
Slow code in UIShowText_b()

* **What is the new behavior (if this is a feature change)?**
Nice and fast code

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
gbdk-2020 has very efficient BCD-based itoa/ltoa implementations. no need for homegrown conversion routines with div/mod, they come out 10 times slower at least.

### CODE REVIEW

**Comment by untoxa** [comment]
old parser was 10 times slower even with itoa(). here is a result of profiling (the same tokenized strings from sample project pass through new and old code):

NEWTOKENS:B0C
OLDTOKENS:6A0F

NEWTOKENS:164C
OLDTOKENS:59D8

NEWTOKENS:148A
OLDTOKENS:654A

NEWTOKENS:6C1
OLDTOKENS:61F6

NEWTOKENS:1886
OLDTOKENS:652E

**Comment by RichardULZ** [comment]
Hell yes, this wasn't as noticeable after we switched to music on interupt (1.2.1 had a 1 frame music stutter on textboxes) but I always thought thought parsing could/should be optimised, a 10x improvement is above and beyond what I expected.

**Comment by untoxa** [comment]
i think i'm done with it :)

**Comment by chrismaltby** [comment]
Awesome speed improvement!! Nice one!

**Pull request merged**
