### PR TITLE
Adding a conditional actor to actor range check event

### PR DESCRIPTION
**Pull request by juliusl**
Signed-off-by: Julius Liu <juliusl@microsoft.com>

* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our [guidelines](/chrismaltby/gb-studio/blob/develop/.github/COMMIT_MESSAGE_GUIDELINES.md)
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
N/A

* **What is the new behavior (if this is a feature change)?**
N/A

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
N/A

* **Other information**:
Addresses #1058

Screeshots:

# Event Configuration
image

# Event Preview
distance_preview_2

# Menu
image

# In Action
tinker

### CODE REVIEW

**Comment by juliusl** [comment]
Some things I was thinking about after working on this, and I'd like to open it up for discussion:

1) I'm not sure if pixel units is accurate or if it should be tile units
2) I think the calculations I'm using could be optimized but I opted for correctness 
3) If this is used in OnUpdate, it can slow perf down, but adding a wait immediately after the event mitigates that, I'm wondering a polling rate field should be added to the event?

**Comment by blurymind** [comment]
i think tile units would be better
optimized is probably better than super accurate
yes some sort of polling rate would also be helpful

It not like we can have tons of actors at once in gb-studio. It already has a limit on that number of actors. Thing is when that limit is almost reached, using this doesnt affect performance much

**Comment by juliusl** [comment]
>  I dont think it needs to be super accurate - just work with minimal input.
(instead of asking you to store player/actor x and y, just ask you to select actor a and select actor b - extract their x/y under the hood and not ask the user to do that) The less manual steps it takes to set up, the better!
optimized is probably better than super accurate

Yep, since I'm adding a new event, I was able to flesh out the UX alot more, this is what it looks like now: 

image

**Comment by juliusl** [comment]
@blurymind 
> yes some sort of polling rate would also be helpful
> 
> 
> 
> Its not like we can have tons of actors at once in gb-studio. It already has a limit on that number of actors. Thing is when that limit is almost reached, using this doesnt affect performance much - and of course the minimum input required to work. The less mandatory input/steps to set up- the less noise in the gui to read the logic and the faster we can set the ai.

Yeah so since I know gbstudio is geared more towards artists, I figured polling rate might be too technical of something to consider up front, and also the interval you want your ai to check could also be considered a narrative characteristic. 

What do you think if we called it "Detection Speed", with options like: (slower, slow, normal, fast, faster, custom)? That way it's consistent with other event options.

**Comment by blurymind** [comment]
Maybe Detection rate? Detect every x ms?

Detection speed works too :) Great job btw

**Comment by blurymind** [comment]
should it have a ><= parameter?

What if we want if distance is greater or equal?

**Comment by pau-tomas** [comment]
Nice work! It reminds me of #606 

A couple of comments:
- Since tiles is the default unit of measure across the app you can leave the field as `Distance` no need to mention `tile units`.
- Would be great to be able to preview the range in the scene (similar to how `Move To` shows a box of the destination position (check `eventsHelpers.ts`).
- Add an option to use a variable for Distance.
- Detection speed is probably not needed as it will overcomplicate the event. A lot of existing events used inside `On Update` will have a hit in performance if there's no wait or vm_idle right after them.

**Comment by juliusl** [comment]
Just letting everyone know that this is still on my todo list, I've just been on vacation will get to back to it this week ~ 

> @pau-tomas Would be great to be able to preview the range in the scene (similar to how Move To shows a box of the destination position (check eventsHelpers.ts). 

Preview would be awesome, I'll take a look at that. I think I should be able to add a variable for distance. 

> @blurymind should it have a ><= parameter?
> 
> What if we want if distance is greater or equal?

That should be doable, I'll try it out and show what it looks like with that option

**Comment by juliusl** [comment]
distance_preview

@pau-tomas  :D

**Comment by juliusl** [comment]
distance_preview_2

@pau-tomas @blurymind  Ok I think I've about covered all of the comments so far, take a look.

**Comment by juliusl** [comment]
@chrismaltby Hey there, I was wondering where do I update documents?

**Comment by blurymind** [comment]
very nice :) I do hope this gets merged

**Comment by pau-tomas** [comment]
Hey @juliusl, thanks for the updates! I tested it again and found a crash when using the event in a non-actor script and trying to preview the distance in the scene. The crash was due to the `$self$` actor being `undefined` in that case. I fixed that bug and took a bit of a different approach to using `actorsLookup` here https://github.com/pau-tomas/gb-studio/commits/fix/pr_1060 if you like that approach, please, feel free to use it.

In that branch also I ran `yarn prettier` on the changed files to ensure they're consistent with (most) of the codebase. (note for myself: document that in the how to contribute list)

**Comment by juliusl** [comment]
@pau-tomas Looks good to me, I'll update my branch

**Comment by juliusl** [comment]
@pau-tomas gentle ping, is there anything else I can do for this PR? :D

**Comment by chrismaltby** [comment]
Hi @juliusl I finally got around to reviewing this, awesome work! Really like the preview :-) 

I made a few minor tweaks to the UI and it seems like you'd missed handling the case when distance was set to a variable rather than a number so I've implemented that, other than that it's all good, happy to merge!

**Comment by juliusl** [comment]
@chrismaltby woohoo! thanks for the fixes and merge 🥳🥳

**Pull request merged**
