### PR TITLE
Feature/dynamic rom sizing

### PR DESCRIPTION
**Pull request by chrismaltby**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Allows the generated ROM size to be dynamic based on the amount of game content.

* **What is the current behavior?** (You can also link to an open issue here)
All ROMs generated by GB Studio are 1MB in size, creating a maximum amount of content that you can add to your game and using much more space than required for smaller games.

* **What is the new behavior (if this is a feature change)?**
GB Studio determines the amount of banks required while compiling your game and sets the ROM size accordingly. The sample project with no modifications is now 256KB

Supported ROM sizes are:
- 128KB
- 256KB
- 512KB
- 1MB
- 2MB
- 4MB
- 8MB

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Hopefully not, but I'd appreciate if anyone could test their projects using this branch and report if there's any issues.

* **Other information**:
This PR is heavily influenced by @RichardULZ and @pau-tomas and is a combination of their suggestions in https://github.com/chrismaltby/gb-studio/pull/408#issuecomment-615390717 and https://github.com/chrismaltby/gb-studio/pull/409 so big thanks to both of them for helping with this feature!

Also I've increased the number of banks that can be used for music from 8 to 16, a better way for allocating music to banks is needed but this should help anyone who is running out of space for now.

### CODE REVIEW

**Comment by pau-tomas** [comment]
Did a quick test with some projects I had around. Most of them works well but I found a glitch in one of the cart we were investigating for `address overflow` from Discord. The project compiles and seems to work well when using the Custom Events 2 changes (#393) but shows a graphical glitch in the menu cursor when using this PR. 

Screenshot 2020-04-18 at 20 04 38 image

I can share the project in private if that's helpful.

**Comment by chrismaltby** [comment]
Thanks for testing this @pau-tomas yeah that issue is very odd. Could you please share the project with me on Twitter and I'll look into it?

**Comment by chrismaltby** [comment]
@RichardULZ I've merged in your music update, as you said I just needed to move the cart size calculation until after the music was compiled so I've put it in `buildProject.js` for now.

@pau-tomas as I was unable to reproduce the graphical glitch from the project you sent me I'm thinking it seems to be a different issue again. Will merge for now and ask if people can test their large projects in the dev build.

**Comment by RichardULZ** [comment]
Getting the cursor issue too on a few large games, it varies location when writing to data_ptrs.h, but not out of bank6...
 ```
#define FRAME_BANK 8
#define FRAME_BANK_OFFSET 16219
#define CURSOR_BANK 6
#define CURSOR_BANK_OFFSET 16308
```
Suspicion i will test if compiling ui first fixes it.

**Comment by RichardULZ** [comment]
Other users are having the same issue on discord. 
I did manage to reorder UI compiling to before other background tiles, which fixed the issue, but likely leaves edge cases.
The more robust quick solution is make sure UI is stored before any script data.
But the underlying issue is only revealed by dynamic rom ordering, perhaps we're storing the incorrect location or bank of this tile?

**Pull request merged**
